[package]
name = "rust-crypt"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.1"
rand = "0.8.5"
argon2 = "0.5.0"
clap = { version = "4.1.8", features = ["derive"] }
anyhow = "1.0.69"